name: Build

on:
  push:
    branches: [ "compiler" ]
  pull_request:
    branches: [ "compiler" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build windows (amd64)
      run: cd fire && GOOS=windows GOARCH=amd64 go build -o fire.amd64.exe

    - name: Build linux (amd64)
      run: cd fire && GOOS=linux GOARCH=amd64 go build -o fire.amd64

    - name: Build linux (arm64)
      run: cd fire && GOOS=linux GOARCH=arm64 go build -o fire.arm64

    - name: Build linux (riscv64)
      run: cd fire && GOOS=linux GOARCH=riscv64 go build -o fire.riscv64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiler
        path: fire/fire.*
