name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install clang
      run: sudo apt update && sudo apt install -y clang llvm

    - name: Build and install
      run: cd fire && go build && sudo mv fire /usr/bin/fire

    - name: Run validation
      run: cd validation && fire validate
